# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u540d\u79f0')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='country.Country', verbose_name='\u4e0a\u4e00\u7ea7')),
            ],
            options={
                'verbose_name': '\u56fd\u5bb6/\u57ce\u5e02',
                'verbose_name_plural': '\u56fd\u5bb6/\u57ce\u5e02',
            },
        ),
    ]
