# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '\u56fd\u5bb6/\u7ec4\u7ec7', 'verbose_name_plural': '\u56fd\u5bb6/\u7ec4\u7ec7'},
        ),
        migrations.AddField(
            model_name='country',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='desc',
            field=models.TextField(blank=True, verbose_name='\u7f51\u7ad9\u7b80\u4ecb'),
        ),
        migrations.AddField(
            model_name='country',
            name='link',
            field=models.URLField(blank=True, verbose_name='\u7f51\u7ad9\u5730\u5740'),
        ),
    ]
