# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20180527_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u7ec4\u7ec7\u540d\u79f0')),
                ('desc', models.TextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('link', models.URLField(blank=True, verbose_name='\u7f51\u7ad9\u5730\u5740')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-c_time',),
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='country',
            name='link',
        ),
        migrations.AddField(
            model_name='orgination',
            name='country',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country', verbose_name='\u6240\u5c5e\u7fa4'),
        ),
    ]
