# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20180530_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orgination',
            new_name='Organisation',
        ),
    ]
