# Generated by Django 2.2.3 on 2019-07-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20190727_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('-c_time',), 'verbose_name': '网站信息'},
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Category', verbose_name='所属类别'),
        ),
        migrations.AlterField(
            model_name='site',
            name='desc',
            field=models.TextField(blank=True, verbose_name='网站简介'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=150, verbose_name='网站名称'),
        ),
    ]
