# Generated by Django 2.2.3 on 2019-08-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_auto_20190730_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家/地区', 'verbose_name_plural': '国家/地区'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
