# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar', verbose_name='\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='user',
            name='site_url',
            field=models.URLField(blank=True, help_text='\u7f51\u5740\u5fc5\u987b\u4ee5http\u5f00\u5934\u7684\u5b8c\u6574\u5f62\u5f0f', verbose_name='\u4e2a\u4eba\u7f51\u5740'),
        ),
    ]
