# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u59d3\u540d')),
                ('birth_date', models.DateField(blank=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u4e66\u540d')),
                ('pub_date', models.DateField(blank=True, verbose_name='\u51fa\u7248\u65e5\u671f')),
                ('authors', models.ManyToManyField(to='box.Author', verbose_name='\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u51fa\u7248\u793e\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u5176\u4ed6', max_length=200, verbose_name='\u4e3b\u9898')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u6458\u8981\u5185\u5bb9')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Book', verbose_name='\u6240\u5c5e\u4e66\u672c')),
                ('subjects', models.ManyToManyField(to='box.Subject', verbose_name='\u6240\u5c5e\u4e3b\u9898')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u8bfb\u4e66\u6458\u8981',
                'verbose_name_plural': '\u8bfb\u4e66\u6458\u8981',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Publisher', verbose_name='\u51fa\u7248\u793e'),
        ),
    ]
