# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '\u4f5c\u8005', 'verbose_name_plural': '\u4f5c\u8005'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-name',), 'verbose_name': '\u4e66\u672c', 'verbose_name_plural': '\u4e66\u672c'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '\u51fa\u7248\u793e', 'verbose_name_plural': '\u51fa\u7248\u793e'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '\u4e3b\u9898', 'verbose_name_plural': '\u4e3b\u9898'},
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u51fa\u7248\u65e5\u671f'),
        ),
    ]
