# Generated by Django 2.2.3 on 2019-07-27 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_book_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thoughts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Entry', verbose_name='读后感'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='box.Book', verbose_name='所属书本'),
        ),
    ]
