# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20180417_2238'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u53d1\u8868\u65f6\u95f4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment_related', to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u4eba')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment_child_comments', to='comments.PostComment', verbose_name='\u7236\u8bc4\u8bba')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.Entry', verbose_name='\u6240\u5c5e\u6587\u7ae0')),
                ('rep_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment_rep_comment', to='comments.PostComment', verbose_name='\u56de\u590d')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u6587\u7ae0\u8bc4\u8bba',
                'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba',
            },
        ),
    ]
