# Generated by Django 2.2.3 on 2019-07-27 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcomment_related', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcomment_child_comments', to='comments.PostComment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='rep_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcomment_rep_comment', to='comments.PostComment', verbose_name='回复'),
        ),
    ]
