# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180501_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='resp_to',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='rep_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment_rep_comment', to='comments.PostComment', verbose_name='\u56de\u590d'),
        ),
    ]
