# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('m_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('excerpt', models.CharField(blank=True, help_text='\u4e0d\u586b\u5199\u5219\u81ea\u52a8\u751f\u6210', max_length=255, verbose_name='\u6458\u8981')),
                ('body', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u6807\u7b7e')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('m_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
