# Generated by Django 2.2.3 on 2019-07-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190727_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-c_time'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
