# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('place', models.CharField(max_length=100, verbose_name='\u8eab\u4efd\u8bc1\u5c5e\u5730')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
